### ISSUE TITLE
does not work with 3.6.1

### ISSUE THREAD

**Issue by prajoshpremdas** [pycontribs/confluence#14]
I tried installing confluence package using pip and asks for version package as explained in the issue https://github.com/pycontribs/confluence/issues/5

Then tried the same by cloning the same from GitHub code and fails with the version again. Could you kindly tell me how to solve this issue or is old bug still open 

P.S: pbr -3.0.1 is installed 

The logs for the error 
**python setup.py**

```
ERROR:root:Error parsing
Traceback (most recent call last):
  File "C:\tools\Anaconda3_64\lib\site-packages\pbr\core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "C:\tools\Anaconda3_64\lib\site-packages\pbr\util.py", line 249, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "C:\tools\Anaconda3_64\lib\site-packages\pbr\hooks\__init__.py", line 25, in setup_hook
    metadata_config.run()
  File "C:\tools\Anaconda3_64\lib\site-packages\pbr\hooks\base.py", line 27, in run
    self.hook()
  File "C:\tools\Anaconda3_64\lib\site-packages\pbr\hooks\metadata.py", line 26, in hook
    self.config['name'], self.config.get('version', None))
  File "C:\tools\Anaconda3_64\lib\site-packages\pbr\packaging.py", line 748, in get_version
    name=package_name))
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between
 the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name confluence was given, but was not able to be found.
error in setup command: Error parsing C:\experiment\confluence_test\confluence\setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or
 access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.Versio
nInfo. Project name confluence was given, but was not able to be found.
```

**Comment by paulwicking** [comment]
@prajoshpremdas As a temporary fix, you can clone the **develop** branch, and install it using pip with
`pip install confluence/`
Note the trailing slash.

**Comment by paulwicking** [comment]
Tests need to be fixed before merging from develop.
