### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by paulwicking** [pycontribs/confluence#16]
CI tests fail due to missing config.ini.
**ConfluenceTests.test_renderContent** fails _with_ config.ini:
```
tests/tests.py::ConfluenceTests::test_renderContent ERROR:root:Failed call to renderContent('ds','65541') : 0 : java.lang.NoSuchMethodException: com.sun.proxy.$Proxy2471.renderContent(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)
FAILED

------- generated xml file: /home/paul/Programming/Python/pycontrib/confluence/build/results.xml --------
=============================================== FAILURES ================================================
__________________________________ ConfluenceTests.test_renderContent ___________________________________

self = <tests.tests.ConfluenceTests testMethod=test_renderContent>

    def test_renderContent(self):
>       result = self.conf.renderContent(page='Welcome to Confluence', space='ds')

tests/tests.py:28: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <confluence.confluence.Confluence object at 0x7f1cf488d5d0>, space = 'ds', page = '65541', a = ''
b = None

    def renderContent(self, space, page, a='', b=None):
        """
            Obtains the HTML content of a wiki page.
    
            :param page: The page name
            :type  page: ``str``
    
            :param space: The space name
            :type  space: ``str``
    
            :return: string: HTML content
            """
    
        try:
            if not page.isdigit():
                page = self.getPageId(page=page, space=space)
            if self._token2:
                return self._server.confluence2.renderContent(self._token2, space, page, a, b)
            else:
                return self._server.confluence1.renderContent(self._token, space, page, a, b)
        except ssl.SSLError as err:
            logging.error("%s while retrieving page %s", err, page)
            return None
        except xmlrpclib.Fault as err:
            logging.error("Failed call to renderContent('%s','%s') : %d : %s", space, page, err.faultCode, err.faultString)
>           raise err
E           Fault: <Fault 0: 'java.lang.NoSuchMethodException: com.sun.proxy.$Proxy2471.renderContent(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)'>

confluence/confluence.py:441: Fault
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================== 1 failed, 2 passed in 0.84 seconds ===================================
```

**Comment by paulwicking** [comment]
Changing the definition of `renderContent` to
`def renderContent(self, space, page, a='', b={"style": "clean"}):`
resolves the `NoSuchMethodException:` error. Test still fails when parsing the result, with an  `xml.parsers.expat.ExpatError: mismatched tag:` error. 

With `b={"style" : "raw"}`, the test fails with an 
`xml.parsers.expat.ExpatError: not well-formed (invalid token):` error.

`not well-formed (invalid token)` with slice:
```
>>> x = parseString(result)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wow/.pyenv/versions/3.6.1/lib/python3.6/xml/dom/minidom.py", line 1968, in parseString
    return expatbuilder.parseString(string)
  File "/home/wow/.pyenv/versions/3.6.1/lib/python3.6/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/home/wow/.pyenv/versions/3.6.1/lib/python3.6/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 85
>>> result[:200]
'<html><head><title>What is Confluence? (step 1 of 9)</title><style default-inline-css>\n\n@import &#39;./imports/global&#39;;\n\n/**\n * RESET\n */\nhtml, body, p, div, h1, h2, h3, h4, h5, h6, img, pre, form'
```

`xml.parsers.expat.ExpatError: mismatched tag:` error:
```
<?xml version="1.0" encoding="utf-8"?><testsuite errors="0" failures="1" name="pytest" skips="0" tests="1" time="1.786"><testcase classname="tests.tests.ConfluenceTests" file="tests/tests.py" line="26" name="test_renderContent" time="1.205399751663208"><failure message="xml.parsers.expat.ExpatError: mismatched tag: line 1, column 880">self = &lt;tests.tests.ConfluenceTests testMethod=test_renderContent&gt;

    def test_renderContent(self):
        result = self.conf.renderContent(page=&apos;Welcome to Confluence&apos;, space=&apos;ds&apos;)
        # tree = ElementTree.fromstring(result)
        # html = lxml.html.fromstring(result)

&gt;       x = parseString(result)

tests/tests.py:32:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

string = &apos;&lt;div id=&quot;ConfluenceContent&quot;&gt;&lt;p style=&quot;text-align: center;&quot;&gt;\xa0&lt;/p&gt;&lt;h2 id=&quot;WelcometoConfluence-WithConfluenceitiseasy...p&gt;&lt;p&gt;&lt;span style=&quot;color: rgb(128,128,128);&quot;&gt;&lt;br/&gt;&lt;/span&gt;&lt;/p&gt;&lt;p style=&quot;text-align: right;&quot;&gt;\xa0 \xa0 \xa0\xa0&lt;/p&gt;&lt;/div&gt;&apos;
parser = None

    def parseString(string, parser=None):
        &quot;&quot;&quot;Parse a file into a DOM from a string.&quot;&quot;&quot;
        if parser is None:
            from xml.dom import expatbuilder
&gt;           return expatbuilder.parseString(string)

../../../.pyenv/versions/3.6.1/lib/python3.6/xml/dom/minidom.py:1968:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

string = &apos;&lt;div id=&quot;ConfluenceContent&quot;&gt;&lt;p style=&quot;text-align: center;&quot;&gt;\xa0&lt;/p&gt;&lt;h2 id=&quot;WelcometoConfluence-WithConfluenceitiseasy...p&gt;&lt;p&gt;&lt;span style=&quot;color: rgb(128,128,128);&quot;&gt;&lt;br/&gt;&lt;/span&gt;&lt;/p&gt;&lt;p style=&quot;text-align: right;&quot;&gt;\xa0 \xa0 \xa0\xa0&lt;/p&gt;&lt;/div&gt;&apos;
namespaces = True

    def parseString(string, namespaces=True):
        &quot;&quot;&quot;Parse a document from a string, returning the resulting
        Document node.
        &quot;&quot;&quot;
        if namespaces:
            builder = ExpatBuilderNS()
        else:
            builder = ExpatBuilder()
&gt;       return builder.parseString(string)

../../../.pyenv/versions/3.6.1/lib/python3.6/xml/dom/expatbuilder.py:925:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = &lt;xml.dom.expatbuilder.ExpatBuilderNS object at 0x7fef4b045e10&gt;
string = &apos;&lt;div id=&quot;ConfluenceContent&quot;&gt;&lt;p style=&quot;text-align: center;&quot;&gt;\xa0&lt;/p&gt;&lt;h2 id=&quot;WelcometoConfluence-WithConfluenceitiseasy...p&gt;&lt;p&gt;&lt;span style=&quot;color: rgb(128,128,128);&quot;&gt;&lt;br/&gt;&lt;/span&gt;&lt;/p&gt;&lt;p style=&quot;text-align: right;&quot;&gt;\xa0 \xa0 \xa0\xa0&lt;/p&gt;&lt;/div&gt;&apos;

    def parseString(self, string):
        &quot;&quot;&quot;Parse a document from a string, returning the document node.&quot;&quot;&quot;
        parser = self.getParser()
        try:
&gt;           parser.Parse(string, True)
E           xml.parsers.expat.ExpatError: mismatched tag: line 1, column 880

../../../.pyenv/versions/3.6.1/lib/python3.6/xml/dom/expatbuilder.py:223: ExpatError</failure></testcase></testsuite>
```

`mismatched tag` with slice:
```
>>> x = parseString(result)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wow/.pyenv/versions/3.6.1/lib/python3.6/xml/dom/minidom.py", line 1968, in parseString
    return expatbuilder.parseString(string)
  File "/home/wow/.pyenv/versions/3.6.1/lib/python3.6/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/home/wow/.pyenv/versions/3.6.1/lib/python3.6/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: mismatched tag: line 1, column 2176
>>> result[2150:2250]
'e-container-version="1"></span></a>\xa0<a href="/confluence/display/ds/Welcome+to+Confluence"><span cla'
```
