### ISSUE TITLE
don't work with python3.4

### ISSUE THREAD

**Issue by yolkov** [pycontribs/confluence#5]
```
python --version
Python 3.4.2
pip -V
pip 8.1.2

pip install confluence
Collecting confluence
  Using cached confluence-0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-12lhm0nx/confluence/setup.py", line 14, in <module>
        from confluence.version import __version__
      File "/tmp/pip-build-12lhm0nx/confluence/confluence/__init__.py", line 9, in <module>
        from version import __version__, __date__
    ImportError: No module named 'version'


pip install -e git+https://github.com/pycontribs/confluence.git@develop#egg=confluence
Obtaining confluence from git+https://github.com/pycontribs/confluence.git@develop#egg=confluence
  Updating ./src/confluence clone (to develop)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/deployer/bot/src/confluence/setup.py", line 125
        **get_metadata(base_path, module_name, 'package_meta.py'),
                                                                 ^
    SyntaxError: invalid syntax
```

**Comment by Barbatrou** [comment]
I have manage to install confluence with python 3.5 by cloning this repo and install it manually without using pip.

**Comment by ssbarnea** [comment]
Due to today's changes this issue is sorted but please note remember issue #7, currently tests are broken because the cloud confluence API login is broken, probably due to RPC deprecation.
